# Generated by Django 5.0.1 on 2024-01-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
