# Generated by Django 4.2.2 on 2023-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("title_en", models.CharField(max_length=255, null=True, verbose_name="title")),
                ("title_fr", models.CharField(max_length=255, null=True, verbose_name="title")),
                ("title_sv", models.CharField(max_length=255, null=True, verbose_name="title")),
                ("title_de", models.CharField(max_length=255, null=True, verbose_name="title")),
                ("short_content", models.CharField(max_length=255, verbose_name="short content")),
                ("short_content_en", models.CharField(max_length=255, null=True, verbose_name="short content")),
                ("short_content_fr", models.CharField(max_length=255, null=True, verbose_name="short content")),
                ("short_content_sv", models.CharField(max_length=255, null=True, verbose_name="short content")),
                ("short_content_de", models.CharField(max_length=255, null=True, verbose_name="short content")),
                ("image", models.ImageField(upload_to="services", verbose_name="image")),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "service",
            },
        ),
    ]
