# Generated by Django 4.2.2 on 2023-07-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.ImageField(blank=True, upload_to="teams/teammembers"),
        ),
    ]
